name: DreeRally Keszites
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Kod letoltese
      uses: actions/checkout@v4
    - name: MSBuild beallitasa
      uses: microsoft/setup-msbuild@v2
    - name: Jatek leforditasa
      run: msbuild DreeRally.sln /p:Configuration=Release /p:Platform=Win32
    - name: Kesz fajlok kimentese
      uses: actions/upload-artifact@v4
      with:
        name: DreeRally_Uj_Exe
        path: |
          **/*.exe
          **/*.dll
